*   DSC530: Week 3
*   3.2 Exercise
*   Marty Hoehler
*   3-30-24

# Exercise 1-1

In [1]:
# Import packages
import numpy as np

In [2]:
# Import data
from os.path import basename, exists

def download(url):
    filename = basename(url)
    if not exists(filename):
        from urllib.request import urlretrieve

        local, _ = urlretrieve(url, filename)
        print("Downloaded " + local)

download("https://github.com/AllenDowney/ThinkStats2/raw/master/code/thinkstats2.py")
download("https://github.com/AllenDowney/ThinkStats2/raw/master/code/thinkplot.py")
download("https://github.com/AllenDowney/ThinkStats2/raw/master/code/nsfg.py")
download("https://github.com/AllenDowney/ThinkStats2/raw/master/code/2002FemPreg.dct")
download("https://github.com/AllenDowney/ThinkStats2/raw/master/code/2002FemPreg.dat.gz")

## Exercises

Select the `birthord` column, print the value counts, and compare to results published in the [codebook](ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/NSFG/Cycle6Codebook-Pregnancy.pdf)

In [3]:
# First, we need to import the table, like they did in the examples.
import nsfg

preg = nsfg.ReadFemPreg()

preg.birthord.value_counts().sort_index()


1.0     4413
2.0     2874
3.0     1234
4.0      421
5.0      126
6.0       50
7.0       20
8.0        7
9.0        2
10.0       1
Name: birthord, dtype: int64

We can also use `isnull` to count the number of nans.

In [4]:
preg.birthord.isnull().sum()

4445

Select the `prglngth` column, print the value counts, and compare to results published in the [codebook](ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/NSFG/Cycle6Codebook-Pregnancy.pdf)

In [5]:
preg.prglngth.value_counts().sort_index()

0       15
1        9
2       78
3      151
4      412
5      181
6      543
7      175
8      409
9      594
10     137
11     202
12     170
13     446
14      29
15      39
16      44
17     253
18      17
19      34
20      18
21      37
22     147
23      12
24      31
25      15
26     117
27       8
28      38
29      23
30     198
31      29
32     122
33      50
34      60
35     357
36     329
37     457
38     609
39    4744
40    1120
41     591
42     328
43     148
44      46
45      10
46       1
47       1
48       7
50       2
Name: prglngth, dtype: int64

To compute the mean of a column, you can invoke the `mean` method on a Series.  For example, here is the mean birthweight in pounds:

In [6]:
preg.totalwgt_lb.mean()

7.265628457623368

Create a new column named <tt>totalwgt_kg</tt> that contains birth weight in kilograms.  Compute its mean.  Remember that when you create a new column, you have to use dictionary syntax, not dot notation.

In [7]:
# Using the 1:.453592 lb to kg converion factor to convert.
# Source for converion factor: https://www.rapidtables.com/convert/weight/pound-to-kg.html
preg['totalwgt_kg'] = preg.totalwgt_lb * .453592

preg.totalwgt_kg.mean()

3.2956309433503437

`nsfg.py` also provides `ReadFemResp`, which reads the female respondents file and returns a `DataFrame`:

In [8]:
download("https://github.com/AllenDowney/ThinkStats2/raw/master/code/2002FemResp.dct")
download("https://github.com/AllenDowney/ThinkStats2/raw/master/code/2002FemResp.dat.gz")

In [9]:
resp = nsfg.ReadFemResp()

`DataFrame` provides a method `head` that displays the first five rows:

In [10]:
resp.head()

caseid  rscrinf  rdormres  rostscrn  rscreenhisp  rscreenrace  age_a  \
0    2298        1         5         5            1          5.0     27   
1    5012        1         5         1            5          5.0     42   
2   11586        1         5         1            5          5.0     43   
3    6794        5         5         4            1          5.0     15   
4     616        1         5         4            1          5.0     20   

   age_r  cmbirth  agescrn  ...  pubassis_i      basewgt  adj_mod_basewgt  \
0     27      902       27  ...           0  3247.916977      5123.759559   
1     42      718       42  ...           0  2335.279149      2846.799490   
2     43      708       43  ...           0  2335.279149      2846.799490   
3     15     1042       15  ...           0  3783.152221      5071.464231   
4     20      991       20  ...           0  5341.329968      6437.335772   

      finalwgt  secu_r  sest  cmintvw  cmlstyr  screentime   intvlngth  
0  5556.717241       2    18     1234     1222    18:26:36  110.492667  
1  4744.191350       2    18     1233     1221    16:30:59   64.294000  
2  4744.191350       2    18     1234     1222    18:19:09   75.149167  
3  5923.977368       2    18     1234     1222    15:54:43   28.642833  
4  7229.128072       2    18     1233     1221    14:19:44   69.502667  

[5 rows x 3087 columns]

Select the `age_r` column from `resp` and print the value counts.  How old are the youngest and oldest respondents?

In [11]:
resp.age_r.value_counts().sort_index()


# Youngest respondents were 15.  Oldest respondents were 44.

15    217
16    223
17    234
18    235
19    241
20    258
21    267
22    287
23    282
24    269
25    267
26    260
27    255
28    252
29    262
30    292
31    278
32    273
33    257
34    255
35    262
36    266
37    271
38    256
39    215
40    256
41    250
42    215
43    253
44    235
Name: age_r, dtype: int64

In [12]:
# Can also find oldest respondents with the max() function:
resp.age_r.max()

44

In [13]:
# Can also find youngest respondents with the min() function:
resp.age_r.min()

15

We can use the `caseid` to match up rows from `resp` and `preg`.  For example, we can select the row from `resp` for `caseid` 2298 like this:

In [14]:
resp[resp.caseid==2298]

caseid  rscrinf  rdormres  rostscrn  rscreenhisp  rscreenrace  age_a  \
0    2298        1         5         5            1          5.0     27   

   age_r  cmbirth  agescrn  ...  pubassis_i      basewgt  adj_mod_basewgt  \
0     27      902       27  ...           0  3247.916977      5123.759559   

      finalwgt  secu_r  sest  cmintvw  cmlstyr  screentime   intvlngth  
0  5556.717241       2    18     1234     1222    18:26:36  110.492667  

[1 rows x 3087 columns]

And we can get the corresponding rows from `preg` like this:

In [15]:
preg[preg.caseid==2298]

caseid  pregordr  howpreg_n  howpreg_p  moscurrp  nowprgdk  pregend1  \
2610    2298         1        NaN        NaN       NaN       NaN       6.0   
2611    2298         2        NaN        NaN       NaN       NaN       6.0   
2612    2298         3        NaN        NaN       NaN       NaN       6.0   
2613    2298         4        NaN        NaN       NaN       NaN       6.0   

      pregend2  nbrnaliv  multbrth  ...  religion_i  metro_i      basewgt  \
2610       NaN       1.0       NaN  ...           0        0  3247.916977   
2611       NaN       1.0       NaN  ...           0        0  3247.916977   
2612       NaN       1.0       NaN  ...           0        0  3247.916977   
2613       NaN       1.0       NaN  ...           0        0  3247.916977   

      adj_mod_basewgt     finalwgt  secu_p  sest  cmintvw  totalwgt_lb  \
2610      5123.759559  5556.717241       2    18      NaN       6.8750   
2611      5123.759559  5556.717241       2    18      NaN       5.5000   
2612      5123.759559  5556.717241       2    18      NaN       4.1875   
2613      5123.759559  5556.717241       2    18      NaN       6.8750   

      totalwgt_kg  
2610     3.118445  
2611     2.494756  
2612     1.899417  
2613     3.118445  

[4 rows x 245 columns]

How old is the respondent with `caseid` 1?

In [16]:
resp.age_r[resp.caseid==1]

1069    44
Name: age_r, dtype: int64

What are the pregnancy lengths for the respondent with `caseid` 2298?

In [17]:
preg.prglngth[preg.caseid==2298]

2610    40
2611    36
2612    30
2613    40
Name: prglngth, dtype: int64

What was the birthweight of the first baby born to the respondent with `caseid` 5012?

In [18]:
preg[preg.caseid==5012]

caseid  pregordr  howpreg_n  howpreg_p  moscurrp  nowprgdk  pregend1  \
5515    5012         1        NaN        NaN       NaN       NaN       6.0   

      pregend2  nbrnaliv  multbrth  ...  religion_i  metro_i      basewgt  \
5515       NaN       1.0       NaN  ...           0        0  2335.279149   

      adj_mod_basewgt    finalwgt  secu_p  sest  cmintvw  totalwgt_lb  \
5515       2846.79949  4744.19135       2    18      NaN          6.0   

      totalwgt_kg  
5515     2.721552  

[1 rows x 245 columns]

In [19]:
# This shows that there is only one pregnancy for CaseID 5012.
preg.totalwgt_lb[preg.caseid==5012]

5515    6.0
Name: totalwgt_lb, dtype: float64

## Exercise 1-2


In [20]:
resp.pregnum.value_counts().sort_index()

0     2610
1     1267
2     1432
3     1110
4      611
5      305
6      150
7       80
8       40
9       21
10       9
11       3
12       2
14       2
19       1
Name: pregnum, dtype: int64

The above table matches the table on pg 11 of the [codebook](https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/NSFG/Cycle6Codebook-Female.pdf)

### Validating 'pregnum' value
First step will be to take advantage of the "preg_map" function supplied by the author of the book:

In [21]:
preg_map = nsfg.MakePregMap(preg)

# This creates a dictionary that maps all the case ids in the 'preg' data frame onto the index numbers. 
# So the count of values in each item should give us the number of pregnancies for each.

In [22]:
# The length function can tell us how many indices are in there for each caseid.  
# Above, we saw that caseid 2298 had 4 pregnancies.  This shows that as well:
len(preg_map[2298])

4

In [23]:
# The value for [pregnum] for caseid 2298 in the resp table is also 4:
resp.pregnum[resp.caseid == 2298]

0    4
Name: pregnum, dtype: int64

### I attempted the validation by creating a data frame with the results from the 'preg_map' function.
 Source for creating a dataframe from an existing dataframe:
https://stackoverflow.com/questions/34682828/extracting-specific-selected-columns-to-new-dataframe-as-a-copy

In [24]:
validationDF = resp[['caseid', 'pregnum']].copy()
validationDF.head()   

caseid  pregnum
0    2298        4
1    5012        1
2   11586        1
3    6794        0
4     616        0

 But when I attempted to add a column that checked the "pregnum" from "resp" against the list function, # I got "'Series' objects are mutable, thus they cannot be hashed" as an error.

####  My attempt:

validationDF['pregnum_preg'] = np.where(validationDF.pregnum != len(preg_map[validationDF.caseid]), "No Match", "Match")

I'm not sure if there's a way to make my dataframe method work.  The author's 'for loop' method is certainly more concise than my dataframe attempt, so it was better to learn his solution, even if my method had worked.

## Exercise 2-1

### Question:
Based on the results in this chapter, suppose you were asked to summarize what you learned about whether first babies arrive late.
* Which summary statistics would you use if you wanted to get a story on the
evening news?
* Which ones would you use if you wanted to reassure an anxious patient?

Finally, imagine that you are Cecil Adams, author of The Straight Dope (http://straightdope.com), and your job is to answer the question, “Do first babies arrive late?”
* Write a paragraph that uses the results in this chapter to answer the question clearly, precisely, and honestly.

### Evening News
I have trouble answering this one, because even if my goal were to reach the evening news, I'm not comfortable taking advantage of statistical ambiguity to get on the news.  (Besides, there are plenty of armchair statisticians that would call me out.)  But assuming I were an unscrupulous individual, I could run with the headline "Your first child will be born later than you expect!" which would be technically true, because mean pregnancy length for first babies is 38.601 weeks and other babies arrive at a mean pregnancy length of 38.523 weeks.  The article could conveniently avoid mentioning that this is a difference of only about 13 hours.

### Anxious Patients
For anxious parents, I would mention that the difference between first children and later children is very small.  I would mention the 13 hours, (difference of the means) because it's easy to understand.  Personally, I'd want to know the Cohen's d statistic to know how the difference of the means relates to the standard deviation, so I could be confident saying "13 hours isn't very big."  But I wouldn't try to explain it to anxious future parents.

### The Straight Dope
For an honest and precise answer, I would say "First babies do arrive slightly later on average.  The mean pregnancy length for first children is 38.601 weeks, compared to 38.523 weeks for other children.  However, this difference in means only amounts to a difference of about 13 hours... only .029 standard deviations.  This is a small difference."  

I would also like to include some data on the statistical significance of the difference of means, which I'd imagine would be low.  But those statistics are for later chapters, I believe.

## Exercise 2-4

In [25]:
# The NSFG preg table has already been loaded above.  
# We'll create a subset for live births, the same way the author did, 
# and subsets that further split between first babies and other births.

live = preg[preg.outcome == 1]
firsts = live[live.birthord == 1]
others = live[live.birthord !=1]

In [26]:
# Mean, Variance and Standard Deviaition for each subset

mean_first = firsts.totalwgt_lb.mean()
mean_first

7.201094430437772

In [27]:
var_first = firsts.totalwgt_lb.var()
std_first = firsts.totalwgt_lb.std()
std_first

1.4205728777207374

In [28]:
mean_others = others.totalwgt_lb.mean()
mean_others

7.325855614973262

In [29]:
var_others = others.totalwgt_lb.var()
std_others = others.totalwgt_lb.std()
std_others

1.3941954762143138

In [30]:
mean_all = live.totalwgt_lb.mean()
mean_all

7.265628457623368

In [31]:
var_all = live.totalwgt_lb.var()
std_all = live.totalwgt_lb.std()
std_all

1.4082934455690168

In [32]:
# Cohen's d statistic
import math

n_first = len(firsts)
n_others = len(others)
pooled_var = (var_first * n_first + var_others* n_others)/(n_first + n_others)
d = (mean_first-mean_others) / math.sqrt(pooled_var)
d

-0.088672927072602

Based on these statistics, we can see that first babies are lighter than other births.  The mean for first babies is about 7.2lbs, and the mean for other births is about 7.36lbs.  Their means differ by about 0.16lbs, or about 2.56oz.  This does not seem like a very big difference either, and the d statistic shows that it is only about .088 of a standard deviation in difference.  This is slightly more of an effect than the pregnancy length that we calculated, but not that much more.